service: rust-sample
provider:
    name: aws
    runtime: rust
    memorysize: 128
    region: ap-northeast-1
plugins:
    - serverless-rust
package:
    individually: true
functions:
    example-function:
        handler: rust_serverless
        events:
            - http:
                path: /
                method: GET
